### ISSUE TITLE
Opensourcing Hoaxy-Botometer repository

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#12]
_From @glciampaglia on May 17, 2018 17:6_

* [x] Merge `frontend/` folder into [Hoaxy frontend repo](/IUNetSci/hoaxy-frontend)
* [x] For the Botometer cache DB, discuss what can be merged into the [Hoaxy backend repo](/IUNetSci/hoaxy-backend) and what should go in the private Botometer repo.
* [x] Migrate history
* [x] Transfer open issues
* [x] Transfer labels and milestones
* [x] Archive Hoaxy-Botometer repo (this will leave it in read-only mode)
* [x] Make sure deployment scripts use new repo and not the old one
* [x] Migrate branch `old_colors` to hoaxy-fronted, which has the design of the website, and call it `deployment`
* [x] @mihaivavram will import the changes in `mihai-dev` (on hoaxy-botometer) branch into `master` here
* [x] Either @benabus or @mihaivavram will test the website to see that everything works, and then can deploy the latest changes
* [x] Delete `backend/` subfolder.

_Copied from original issue: IUNetSci/hoaxy-botometer#257_

**Comment by glciampaglia** [comment]
* [x] Migrate history
* [ ] Transfer open issues
* [x] Transfer labels and milestones
* [ ] Archive Hoaxy-Botometer repo (this will leave it in read-only mode)

**Comment by glciampaglia** [comment]
I have imported the branches `old_colors` and `mihai-dev` from `hoaxy-botometer`. I have renamed `old_colors` to `deployment`. @mihaivavram feel free to merge your branch into master. I have already deleted `backend/*` and pushed the changes on master.

**Comment by mihaivavram** [comment]
Great! @benabus I have finished adding my changes from `mihai-dev` to `master`.

**Comment by mihaivavram** [comment]
All of the tasks as part of this site have been taken care of, closing, and we can re-open if anything comes up.
