### ISSUE TITLE
Fix cron job script that fetches required botscore calculation data

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#19]
_From @benabus on April 19, 2018 17:2_

This script needs to run on the right machine and connect to the correct database.  Currently, we think it's using Recall. 

It should run on Lenny and connect to the postgres on Lenny.  

_Copied from original issue: IUNetSci/hoaxy-botometer#240_

**Comment by yangkcatiu** [comment]
Moved to [Botometer/botometer-database#6](https://github.iu.edu/Botometer/botometer-database/issues/6).
