### ISSUE TITLE
Is this up to date?

### ISSUE THREAD

**Issue by rogeriochaves** [IUNetSci/hoaxy-frontend#2]
Apparently this repo isn't updated for many months, and by looking at the source code of the website you are now using vuejs, which doesn't exist in this repo

Could you push the latest version or point me in the right direction?

**Comment by glciampaglia** [comment]
Hi Rogério, for collaboration purposes the team decided to develop the new frontend in a [different repository](/IUNetSci/hoaxy-botometer/) repository. However we are planning on porting back the new version into this repository, to make it easier for people like you to find the code. Feel free to follow the following issue to keep track of the code migration: https://github.com/IUNetSci/hoaxy-botometer/issues/257

Closing for now.

**Comment by filmenczer** [comment]
@rogeriochaves we are in the midst of merging the latest version into this repo. There is a new issue for this: https://github.com/IUNetSci/hoaxy-frontend/issues/12
