### ISSUE TITLE
Add a test to make sure API never returns IP address

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#21]
_From @yangkcatiu on September 21, 2017 19:31_

IP address must not be made public, use regex to make sure nothing looks like IP address will be returned.

_Copied from original issue: IUNetSci/hoaxy-botometer#77_

**Comment by yangkcatiu** [comment]
Moved to [Botometer/botometer-database#7](https://github.iu.edu/Botometer/botometer-database/issues/7).
