### ISSUE TITLE
Remove the database API from Carl after the API on Lenny proves to be stable

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#22]
_From @yangkcatiu on May 15, 2018 21:38_

Right now the API is running on both Carl and Lenny. The queries for the scores will still go to https://hoaxy.iuni.iu.edu/hoaxy-botometer/api/scores which is handled by Carl so the frontend won't need to change anything. Carl then will decide which API to point to, right now it points to Lenny. We can easily point it back to the API on Carl if something is wrong. After the launch and the API proves to be working well on Lenny, the API will be removed from Carl with the following steps:

- [ ] Stop the process in supervisord
- [ ] Remove the configuration in /etc/supervisor.config
- [ ] Remove the codes

_Copied from original issue: IUNetSci/hoaxy-botometer#255_

**Comment by yangkcatiu** [comment]
Moved to [Botometer/botometer-database#8](https://github.iu.edu/Botometer/botometer-database/issues/8).
