### ISSUE TITLE
Prioritizing order in which bot scores are updated 

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#26]
I do not remember if we discussed this in the past... When I click the Update Bot Scores button, 20 nodes at a time are updated. Could we do this in order of decreasing out-strength (ie node size)? That would be much more useful than the current random order, especially when most or all nodes are white.

**Comment by benabus** [comment]
Before the cache is queried, the nodes are sorted by size, so the top 50 largest nodes are checked first.
