### ISSUE TITLE
Update FAQ about Twitter search

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#27]
See email from Luiza Bandeira:

- [x] We should specify the limit not only in terms of days but also in terms of number of tweets, based on max number of queries we can submit to API: "7 days or XXX tweets, whichever comes first"
- [x] Clarify how one can use Twitter Search operators in the Hoaxy search box: provide example?
- [x] Reply to Luiza Bandeira

**Comment by benabus** [comment]
https://hoaxy.iuni.iu.edu/faq.html#faq-twitter-search

apparently, advanced search terms weren't actually working.  Queries were being accidentally double encoded.
