### ISSUE TITLE
"Offline" / Snapshot mode for saving visualizations instead of simple queries.

### ISSUE THREAD

**Issue by benabus** [IUNetSci/hoaxy-frontend#33]
The hoaxy visualization component could feature an "offline" mode where the visualization takes in existing data rather than relying on search results.  Existing data could be in the form of a localStorage cache in the browser, or an external, uploaded file (a .hoaxy file, perhaps?).  Users could snapshot the visualization data at a specific point in time and re-render just the visualization without having to re-run the query.

This solves a number of problems:

1.  Hoaxy cannot visualize twitter searches more than 7 days in the past.  Users are unable to review old queries because submitting the query again will only search the past 7 days, rather than the time span that was previously looked at.  If the visualization uses existing data rather than submitting a new query to twitter, the resulting visualization would look exactly as it did when the user first submitted that query and saved the results.

2.  Twitter TOS prevents Hoaxy (us) from saving results retrieved through a user's account.  If the visualization data is stored by the user on the client side (either in the browser's local storage or as an external file), it's the user saving the data to the user's own machine.  Hoaxy servers aren't caching anything and are not serving the collected data to any additional users, so we should be in the clear.

3.  In order to save visualizations, the user needs to run the query in the browser and manually save the image once the visualization is complete.  If instead of saving an image, we're just saving the data, there's no need to render anything in the browser, therefore, the saving could be automated.

4.  Saved images are no longer interactive.  If we're saving the data and not the images, then every time the visualization is re-rendered, it would be interactive again since it's not a static image.

5.  Rerunning many queries (for instance, if a news room wants to pull up a bunch of visualizations at once) will cause users to hit rate limits.  Because rate limits are primarily a server-side issue when hitting an API, if all the re-rendering snapshots are done client-side, this becomes a non-issue.

Potential problems with this solution: 

1. Working with local files inside a website can be tricky.  However, browser file apis are continuously improving.  This might be a non-issue after a little bit more research.

2.  Saving a snapshot of the data would save all the data for everything visualized.  Upon re-rendering the data, there could be deleted tweets in that snapshot and twitter may have an issue with us displaying deleted tweets.  One potential solution is to do the same "rehydration" check that we do with OSoMe to determine if a tweet still exists before displaying it.  This also may be a non-issue because we aren't saving the tweets.  The burden of deleting tweets might be on the client who is saving the snapshot rather than Hoaxy, which is just displaying them.  And this might not even matter since the data comes from the Search API and not from GNIP like OSoMe.

3.  Clients could manually alter the data and visualize false/misleading snapshots.  There's not a lot we can do about this.  Potentially, we could use some kind of encryption so that the data is not saved in plain text, but client side encryption isn't super secure.

We could do a lot with this sort of system and it would probably be better discussed in person.

**Comment by filmenczer** [comment]
Done!
