### ISSUE TITLE
Add bot scores to export CSV

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#34]
Per email from <emmibevensee@email.arizona.edu>, could we do this?

**Comment by benabus** [comment]
We can definitely probably do this.  I believe the original export functionality was added before we added the botscores.  Should be trivial, but I'll look into it to make sure.

**Comment by filmenczer** [comment]
If/when this is done. let's email Emmi Clay Bevensee <emmibevensee@email.arizona.edu> to let her know.

**Comment by benabus** [comment]
Successfully added botscores to the export.  We can close this issue once Emmi Clay Bevensee is notified.

**Comment by filmenczer** [comment]
Thanks @benabus! I emailed Emmi.
