### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#40]
A user asked: "I've logged into your service but was wondering how do I log out of your service with the twitter account I signed in with?"

Although we do not keep any information about users when they authenticate/authorize via Twitter, we should probably provide a logout option as we do for Botometer.

Perhaps we need to use one of these?
* https://developer.twitter.com/en/docs/basics/authentication/api-reference/invalidate_bearer_token
* https://developer.twitter.com/en/docs/basics/authentication/api-reference/invalidate_access_token

**Comment by benabus** [comment]
I think this is less a technical issue and more of a "We just never thought about it" issue.  It is certainly something we should add.

**Comment by filmenczer** [comment]
We decided to implement this in the same way as it is done on the Botometer site, namely a menu item.

**Comment by marcmccarty** [comment]
Completed, with CSS edits to make the header align based on the login/logout button as suggested at today's meeting (3/27/19). Other CSS edits were made on buttons to make them more uniform.
