### ISSUE TITLE
Fix language-dependent bot score

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#43]
Twitter user object no longer has `lang` field (it is null) so we are wrongly assuming languange is non-English and using universal score.

FIX: read the `lang` from tweets that are obtained either from the Hoaxy API (for Hoaxy search) or from the Twitter API (for Twitter search). Botometer now uses the majority language out of 200 tweets, so we could follow the same idea; or if too complicated, we could just get the language from the latest tweet.

**Comment by marcmccarty** [comment]
Commit 3d631c4 on deployment branch handles this and #44.
Still need to put it on master for the sake of future hoaxy users (#45).
