### ISSUE TITLE
Replace old mashap base URL with rapidAPI

### ISSUE THREAD

**Issue by yangkcatiu** [IUNetSci/hoaxy-frontend#44]
https://p.mashape.com => https://p.rapidapi.com

**Comment by marcmccarty** [comment]
Commit 3d631c4f3b8ddd8dba547ea979fa2697c1a08043 on deployment branch handles this and #43.
Still need to put it on master for the sake of future hoaxy users (#45).

**Comment by filmenczer** [comment]
Also update the HTTP headers using 'Mashape' or 'MASHAPE'. For new headers see https://docs.rapidapi.com/docs/headers-sent-by-mashape-proxy2

**Comment by marcmccarty** [comment]
Changed config file to have `X-RapidAPI-Key` and changed variable names to include `rapidapi` for consistency.

Tested and working on Hoaxy live as of this message.

**Comment by yangkcatiu** [comment]
Please also update the README about mashape=>rapidAPI
