### ISSUE TITLE
Discuss pros/cons of using a CDN like unpkg.com

### ISSUE THREAD

**Issue by marcmccarty** [IUNetSci/hoaxy-frontend#46]
We should discuss at a meeting about whether it makes sense for Hoaxy to rely on a CDN for the dependencies.

For example:
------------------------
**Pros**: 
 - can automatically update which prevents security vulnerabilities
 - takes away minor server load and should be faster

**Cons**: 
 - could update to a version that deprecates a feature we're using
 - could go down (if we go down, the whole site does, but this adds a second point of failure)

**Comment by marcmccarty** [comment]
This may be a "best of both worlds" option?:
https://www.hanselman.com/blog/CDNsFailButYourScriptsDontHaveToFallbackFromCDNToLocalJQuery.aspx

We're seeing if there's a more recent example of something like this, too.

**Comment by marcmccarty** [comment]
RequireJS (https://requirejs.org/docs/api.html):
`When run in a browser, paths fallbacks can be specified, to allow trying a load from a CDN location, but falling back to a local location if the CDN location fails to load.`

**Comment by filmenczer** [comment]
We created the issue because the CDN was down and this slowed down Hoaxy. It was fixed quickly. We discussed whether to change our use of CDNs. Seems like a rare problem. Closing for now, will reopen if the problem occurs again.
