### ISSUE TITLE
Language filtering

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#47]
In Twitter search, is there a way to not do any language filtering by not specifying the language? If so, that should be the Hoaxy default ('Any' rather than 'English'). That way one would get all tweets irrespective of language, by default.

**Comment by filmenczer** [comment]
We discussed and decided to add the 'Any' option, but *not* make it the default. The default will remain English. If user selects 'Any', we will not send the language filter parameter. In that case we will use the universal bot scores.

**Comment by marcmccarty** [comment]
First checkbox solved by commit 99471c922d753cc45478ff421432b0e1d99466e0

**Comment by filmenczer** [comment]
We went ahead with this even though #50 still needs to be finalized.
