### ISSUE TITLE
Fix way to decide English/Universal bot score

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#50]
Currently we use the language filter to decide. A better, if more complicated solution would be to extract the language from one (say, the most recent) tweet by the account being checked.  

**LOW PRIORITY**

**Comment by ChrisTorresLugo** [comment]
We just found another issue related to this.

Currently, the hashtag #basichumanright is at the top of the results of BotSlayer. However, when we try to look at it using Hoaxy, it says: "There was not enough data to create a network graph. Try selecting more popular articles and trying again."

When we looked up the hashtag using Twitter search, the results are for tweets that are only using hashtags. For example,

<img width="443" alt="basichumanright" src="https://user-images.githubusercontent.com/7763583/63031283-ce237680-be81-11e9-8db2-2a89e24d193c.png">

These tweets don't have text outside of the hashtags, which aren't parsed to extract language. Therefore, it is not possible to visualize these kind of hashtags using Hoaxy.

**Comment by filmenczer** [comment]
If the latest tweets does not have a language (as in the example above with only hashtags), then we can assume 'universal' by default.

**Comment by filmenczer** [comment]
Defer decision until we decide whether we replace Botometer by BotometerLite in Hoaxy.

**Comment by filmenczer** [comment]
@benabus will take on this task

**Comment by filmenczer** [comment]
Instead of dealing with this in the front-end, when v4 of the API goes live we can just read the majority language from the API output.

Alternatively, in the longer term, we can disconnect Hoaxy from Botometer entirely and use BotometerLite instead.

**Comment by benabus** [comment]
Switched frontend to use botometer v4 api which has the majority language built in.
