### ISSUE TITLE
Fix timestamps of exported/imported data

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#51]
Currently the front end assumes local time, which works if data is exported/imported from the same time zone. But otherwise (eg if the data originates from a BotSlayer instance) the client would not know the time zone.

To fix this, the front end should always use GMT when exporting/importing, and convert to local time in the front end.

Also check that the times shown on the timeline are correct (eg, not ignoring daylight saving).

**Comment by marcmccarty** [comment]
I believe I've resolved this, but we can/should reopen if anyone finds any errors.
