### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by lucmski** [IUNetSci/hoaxy-frontend#52]
Hi guys,

Hope you are all well !

Would be awesome to have a **Dockerfile** to bootstrap the frontend ^^

Cheeers,
L

**Comment by chathuriw** [comment]
@lucmski Do you have any instruction for the frontend docker ? I followed your repository https://github.com/lucmski/hoaxy-frontend and the Dockerfile in https://gist.github.com/lucmski/b4a143b0bf026448f159e6bf463ed0c2.

**Comment by lucmski** [comment]
You just have to set your variables in the js files then `docker-compose up`

**Comment by chathuriw** [comment]
@lucmski thank you for the contribution. It works perfectly with the updated configuration. Please send us a pull request.

**Comment by lucmski** [comment]
https://github.com/IUNetSci/hoaxy-frontend/pull/53 already done :-)
