### ISSUE TITLE
language parameter not passed for social links

### ISSUE THREAD

**Issue by lucmski** [IUNetSci/hoaxy-frontend#56]
Hi guys,

Hope you are all well !

The language parameter is not passed when sharing via facebook or twitter.

```
Hoaxy: How claims spread online https://hoaxy.iuni.iu.edu/#query=%23alicem&sort=mixed&type=Twitter
```

Cheers,
L

**Comment by marcmccarty** [comment]
Good point. I'm working on documenting Hoaxy, but after that is complete, I will make this a top priority (if only because it should be a quick and easy fix). Thanks, L.

-- Marc

**Comment by marcmccarty** [comment]
Commit 0087d56421501b2af3204982d4d4e10317519210 in the `master` branch should handle this issue in your use case and in most others, I think.
