### ISSUE TITLE
Date string too long in timeline

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#66]
It gets cut off on small screens; consider splitting into two lines (date and time).

**Comment by filmenczer** [comment]
We decided that this is too hard as it is due to D3 internals. Won't fix. But will shorten the string by moving from am/pm to 24h format.

**Comment by marcmccarty** [comment]
Date-time is now in this format:

`MM/DD/YYYY HH:MM` where `HH` is 24-hour, like military time.
