### ISSUE TITLE
When sending large post requests to Hoaxy, nothing happens

### ISSUE THREAD

**Issue by benabus** [IUNetSci/hoaxy-frontend#70]
When BotSlayer sends a large request to Hoaxy frontend for visualization, it takes a while to load and then does nothing.

My suspicion is that there is a maximum limit set in the PHP config which prevents POST requests over a certain size from being processed.  

As a reminder, Hoaxy frontend is primarily a browser-based javascript application which typically pulls in data from AJAX requests.  It uses PHP to echo POST request data to the page so that other applications can POST data and visualize external data.

**Comment by filmenczer** [comment]
Short-term fix is to increase the value (see https://www.a2hosting.com/kb/developer-corner/php/using-php.ini-directives/php-maximum-upload-file-size)

Long-term, we should figure out what is a reasonable maximum size given a dense network with the maximum number of nodes.

We should also double-check that the network is properly trimmed by BotSlayer before being sent to Hoaxy for visualization.

**Comment by benabus** [comment]
Short term solution implemented.  Changed max php post size to 20mb.

**Comment by filmenczer** [comment]
Closing for now. It seems to handle well the largest entities on the BLM instance (20k+ accounts, 40k+ tweets) which generate files around 10-15MB. 

We can reopen in case we run into size problems again.

**Comment by filmenczer** [comment]
This may be a problem again since the move to Lisa (see https://github.iu.edu/truthy-team/BotSlayer/issues/325). Reopening.

**Comment by benabus** [comment]
This was not the cause of the BotSlayer malfunction.  (See https://github.iu.edu/truthy-team/BotSlayer/issues/325)
