### ISSUE TITLE
Links on homepage

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#71]
What is the purpose of the 'Visualize | Dashboard' links on the homepage under the title and byline? There is already a link to the dashboard in the menu, and the visualize link is to the homepage.

**Comment by benabus** [comment]
This looks like some code that was accidentally merged from the un-branded branch into the hoaxy branded branch.  The master  branch with no branding doesn't have a menu, so the dashboard link was included below the header.

This can be removed.

**Comment by benabus** [comment]
Removed extra links on hoaxy homepage in deployment branch.  https://hoaxy.iuni.iu.edu/
