### ISSUE TITLE
Data import help

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#72]
We need instructions on how to upload/import network data to visualize. We need to specify the format of the file and provide an example. Ideally, we add an item to the FAQ and a link to it when users click on the 'import data' button...

**Comment by filmenczer** [comment]
Add to FAQ after the question about 'exporting' that you can 'import' those files...

**Comment by filmenczer** [comment]
Also should we use a standard language for the data file, eg GraphML or GML?

**Comment by benabus** [comment]
Added 2 faq items:  https://hoaxy.iuni.iu.edu/faq.php#faq-q30
