### ISSUE TITLE
Article mode is broken?

### ISSUE THREAD

**Issue by ChrisTorresLugo** [IUNetSci/hoaxy-frontend#85]
If we use Hoaxy's Article mode, in this case selecting the last article on the Popular Fact-Checks, and visualize it:

<img width="1116" alt="Screen Shot 2020-10-23 at 2 42 31 PM" src="https://user-images.githubusercontent.com/7763583/97324386-29077a80-1848-11eb-97e3-15f629ea4bd4.png">

Per the cumulative panel, the network that comes up has 2,466 tweets.

<img width="1440" alt="Screen Shot 2020-10-23 at 2 42 55 PM" src="https://user-images.githubusercontent.com/7763583/97324424-315fb580-1848-11eb-98b4-aa8a98c2501c.png">

However, if we look at the 'article visualized' button:

<img width="1162" alt="Screen Shot 2020-10-23 at 2 43 16 PM" src="https://user-images.githubusercontent.com/7763583/97324454-391f5a00-1848-11eb-962b-64af56d21a95.png">

We can see:

- the article that is check-marked is not the same one that we originally clicked (the original one can be seen below, having 664 tweets)
- the number of tweets for the incorrectly check-marked article matches the number of tweets that we saw on the network

**Comment by filmenczer** [comment]
It was not a bug, just poor design; keeping as-is for now.
