### ISSUE TITLE
Update description of the UI

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#89]
To decrease confusion about differences between the Twitter and Article search mode, we should have a clear description at the top of the two next to radio buttons. The description for Twitter could be "Visualize the spread of information on Twitter" and the description for Article could be our current header. 

The header would go away. 

The search box should have default queries that are different depending on the search mode. For Twitter we can keep the current "example: vaccines" and for Article we could use "example: breaking: the earth is flat"

**Comment by filmenczer** [comment]
Common text (above buttons):

Visualize the spread of information on Twitter

Descriptions next to the buttons:

Twitter: Search Twitter content from the past 7 days
Articles: Search articles from low-credibility and fact-checking sources

Plus add '?' linking to FAQ

**Comment by filmenczer** [comment]
A few issues:
- [ ] Button size not wide enough (wraps with large fonts)
- [ ] Buttons on lower search box do not match
- [ ] FAQ update is not complete
- [ ] On Article Search, nodes are not colored by bot scores

Also Article Search is unbearably slow. Probably database issue we must address!!

**Comment by benabus** [comment]
Please check the FAQ again.  There was a git conflict that overwrote a few of the changes.  It should be fixed now, along with the botscore colors.

Article Search is slow because of RapidAPI.  I suspect that we'll need to change the base URL in RapidAPI to "https://hoaxy.osome.iu.edu" rather than "hoaxy.iuni" to prevent unnecessary redirects.

**Comment by filmenczer** [comment]
The FAQ still refers to "Twitter mode".

I checked RapidAPI and the baseline URL is "https://hoaxy.osome.iu.edu/hoaxy/" right now. Response is unacceptably long (even timing out).

**Comment by sarahbeverton** [comment]
The FAQ should all be updated now and the buttons are wider - let us know if you'd like any more visual or content changes (we'll also look into the slowness of Article Search).

**Comment by filmenczer** [comment]
Thanks! This is what the buttons look like on my laptop (this is probably due to my font settings/screen resolution):
<img width="1096" alt="Screen Shot 2021-05-17 at 8 33 00 PM" src="https://user-images.githubusercontent.com/10651090/118572761-2bcbad80-b74f-11eb-8b2a-260cb83dd77d.png">

Thank you also for looking at the slow response.

**Comment by sarahbeverton** [comment]
![Hoaxy_buttons_width](https://user-images.githubusercontent.com/51892802/118658692-9f56d480-b7ba-11eb-8cda-d28c25adf408.PNG)
Here is what the buttons look like on my screen. I can make them wider, but they might start to look a little too wide with most default font settings. Let me know what you think.

**Comment by sarahbeverton** [comment]
I fixed the search buttons so they look nicer with larger font sizes.
