### ISSUE TITLE
In the CSV, include botscores for the two users present in the row/edge of the network

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#9]
_From @mihaivavram on February 25, 2018 16:54_

The `from_user_id` and `to_user_id` fields refer to users which would be nice if we could include in the CSV their respective botscores that can be seen in the visualization.

_Copied from original issue: IUNetSci/hoaxy-botometer#212_

**Comment by marcmccarty** [comment]
Closing since some commits from March of this year addressed this.
